### ISSUE TITLE
Package resource name is mismatched.

### ISSUE THREAD

**Issue by yoneken** [DaikiMaekawa/hector-slam-example#3]
Because of [a ros recommendation](http://wiki.ros.org/Names#Valid_Names-1), the last commit which I requested changed the package resource name as "hector_slam_example" from "hector-slam-example".
However, this causes a problem to build now.

Could you return the name to "hector-slam-example" at https://github.com/DaikiMaekawa/hector-slam-example/blob/master/package.xml#L3 and https://github.com/DaikiMaekawa/hector-slam-example/blob/master/CMakeLists.txt#L2 , or change the project name to "hector_slam_example" on GitHub?

**Comment by DaikiMaekawa** [comment]
:+1: I agree with your opinion. BTW,  did not care naming rule because this repository is sandbox.

**Comment by yoneken** [comment]
Thank you so much!
